[package]
name = "elkridge"
version = "0.1.0"
authors = ["Sean Gallagher <stgallag@gmail.com>"]

[dependencies]
fuse = "^0.3.1"
rusqlite = "0.19.0"
clap = "2.33.0"
failure = "0.1.5"
failure_derive = "0.1.5"
serde_derive = "1.0.94"
env_logger = "0.6.2"
time = "0.1.42"
libc = "0.2.58"